
spring.mesages.basename=messages
spring.datasource.username=root
spring.datasource.password=mysql
spring.datasource.url=jdbc:mysql://localhost:3306/magazyn_db
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Odblokowuje wszystkie punkty ko\u0144cowe Actuatora (do cel\u00F3w deweloperskich)
management.endpoints.web.exposure.include=health,info
# Dodaje szczeg\u00F3\u0142y stanu bazy danych
management.endpoint.health.show-details=always
# Wystawia punkty info i health na zewn\u0105trz (przez HTTP)
# W\u0142\u0105cza standardowe informacje o \u015Brodowisku (opcjonalnie) [cite: 656]
management.info.env.enabled=true
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true